site: kpshtm
title: knowledge based
description: >-
  my personal blog and random though
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Jakarta
# repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: light # default theme "dark" | "light"

author:
  name: Hafiz C.
  bio: wkwkwk.. under construction
  username: kopishitam | apiz19 # general username
  github: apiz19 # github username
  twitter: kopishitam # twitter username
  email: kopishitam@disroot.org # email adress

# URL settings
url: "https://apiz19.github.io" #
baseurl: "" # leave blank if not wishd
# permalink: "https://apiz19.github.io/blog"
# permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
